sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: localhost
      port: 6379
  wechat:
    appid: wxb046f5e1370e6ffc
    secret: 79768e8b099ab0dee2cc98046c418681
